version: "3.9"

services:
  app:
    build: .
    container_name: go-fiber-movie-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
